version: '3.1'

services:

  db:
    container_name: leoturnier_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres/import:/import
    networks:
      - postgres
  auth_db:
    container_name: leoturnier_auth_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
  auth:
    container_name: leoturnier_auth
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command:
      - start --import-realm --http-port 8443
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth_db
      DB_DATABASE: auth_db
      DB_USER: app
      DB_SCHEMA: public
      DB_PASSWORD: app
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    ports:
      - "8443:8443"
    depends_on:
      - auth_db

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8090:8080

# https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
#  pgadmin:
#    container_name: leoturnier_pgadmin
#    image: dpage/pgadmin4:5.5
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - ./db-postgres/pgadmin:/root/.pgadmin
#    ports:
#      - 8090:80
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge