POST http://localhost:8080/api/tournamentMode
Authorization: Basic admin adminpwd
Content-Type: application/json

{
  "name": "KO"
}

###

PUT http://localhost:8080/api/tournamentMode?id=1
Content-Type: application/json

{
  "name": "Group"
}

###

GET http://localhost:8080/api/tournamentMode?id=1

###

GET http://localhost:8080/api/tournamentMode

###

DELETE http://localhost:8080/api/tournamentMode?id=1