version: '3.1'

services:

  db:
    container_name: leoturnier_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres/import:/import
    networks:
      - leoturnier
  auth_db:
    container_name: leoturnier_auth_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    networks:
      - leoturnier
  auth:
    container_name: leoturnier_auth
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command:
      - start --import-realm --http-port 8443
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth_db
      DB_DATABASE: auth_db
      DB_USER: app
      DB_SCHEMA: public
      DB_PASSWORD: app
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    ports:
      - "8443:8443"
    networks:
      - leoturnier
    depends_on:
      - auth_db
  backend:
    container_name: leoturnier_backend
    image: ghcr.io/htl-leonding-project/leo-turnier-backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - auth
    networks:
      - leoturnier
  frontend:
    container_name: leoturnier_frontend
    image: ghcr.io/htl-leonding-project/leo-turnier-frontend:latest
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - leoturnier


networks:
  leoturnier:
    driver: bridge